phpbbmodders_wiki_index:
    path: /wiki/
    defaults: { _controller: phpbbmodders.wiki.overview:base }

phpbbmodders_wiki_article:
    path: /wiki/{article}
    defaults: { _controller: phpbbmodders.wiki.main:article, article: "" }


