parameters:
    tables.wiki.article: '%core.table_prefix%wiki_article'

services:
    _defaults:
        public: true

    phpbbmodders.wiki.overview:
            class: phpbbmodders\wiki\controller\overview
            arguments:
                - '@auth'
                - '@controller.helper'
                - '@dbal.conn'
                - '@request'
                - '@template'
                - '@user'
                - '@phpbbmodders.wiki.edit'
                - '@phpbbmodders.wiki.compare'
                - '@phpbbmodders.wiki.view'
                - '%core.root_path%'
                - '%core.php_ext%'
                - '%tables.wiki.article%'

    phpbbmodders.wiki.main:
        class: phpbbmodders\wiki\controller\main
        arguments:
            - '@auth'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbmodders.wiki.delete'
            - '@phpbbmodders.wiki.edit'
            - '@phpbbmodders.wiki.compare'
            - '@phpbbmodders.wiki.view'
            - '%core.root_path%'
            - '%core.php_ext%'
    phpbbmodders.wiki.listener:
        class: phpbbmodders\wiki\event\listener
        arguments:
            - '@auth'
            - '@controller.helper'
            - '@notification_manager'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
    phpbbmodders.wiki.edit:
        class: phpbbmodders\wiki\wiki\edit
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '%tables.wiki.article%'
            - '%core.root_path%'
            - '%core.php_ext%'
    phpbbmodders.wiki.compare:
        class: phpbbmodders\wiki\wiki\compare
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '%tables.wiki.article%'
            - '%core.root_path%'
            - '%core.php_ext%'
    phpbbmodders.wiki.delete:
        class: phpbbmodders\wiki\wiki\delete
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@controller.helper'
            - '@user'
            - '%tables.wiki.article%'
    phpbbmodders.wiki.view:
        class: phpbbmodders\wiki\wiki\view
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@phpbbmodders.wiki.compare'
            - '@phpbbmodders.wiki.edit'
            - '%tables.wiki.article%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@phpbbmodders.wiki.links'
    phpbbmodders.wiki.links:
        class: phpbbmodders\wiki\wiki\links
        arguments:
            - '@dbal.conn'
            - '%tables.wiki.article%'
    phpbbmodders.wiki.wikilink_listener:
        class: phpbbmodders\wiki\event\wikilink_listener
        arguments:
            - '@controller.helper'
            - '@language'
            - '@phpbbmodders.wiki.links'
        tags:
            - { name: event.listener }

    phpbbmodders.wiki.notification.type.article_edit:
        class: phpbbmodders\wiki\notification\article_edit
        shared: false
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    phpbbmodders.wiki.text_reparser.article_text:
        class: phpbbmodders\wiki\textreparser\plugins\article_text
        arguments:
            - '@dbal.conn'
            - '%tables.wiki.article%'
        calls:
            - [set_name, [phpbbmodders_wiki_article]]
        tags:
            - { name: text_reparser.plugin}